// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQRFxr9AJufEXWpTBop24lP0VGLmTbtas',
    appId: '1:989114150742:android:4148e53d2dbb55ac7570f7',
    messagingSenderId: '989114150742',
    projectId: 'chat-app-8fb90',
    storageBucket: 'chat-app-8fb90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxg3V-8H-S1lZbpUQBcHT4W-4M-kQszLc',
    appId: '1:989114150742:ios:3c9a0213fe7ee2dd7570f7',
    messagingSenderId: '989114150742',
    projectId: 'chat-app-8fb90',
    storageBucket: 'chat-app-8fb90.firebasestorage.app',
    iosBundleId: 'com.example.chatProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkS7C-wkleixF8GZ6VIsNPGGVh9iD00vU',
    appId: '1:989114150742:web:31c8dd4a8ff4cd717570f7',
    messagingSenderId: '989114150742',
    projectId: 'chat-app-8fb90',
    authDomain: 'chat-app-8fb90.firebaseapp.com',
    storageBucket: 'chat-app-8fb90.firebasestorage.app',
  );
}
